_BASE_: ./convnext_large_eval_ade20k.yaml
MODEL:
  FROZEN_SEG:
    CLIP_MODEL_NAME: "RN50x64"
    CLIP_PRETRAINED_WEIGHTS: "openai"
    EMBED_DIM: 1024
    ENSEMBLE_ON_VALID_MASK: True
  MASK_FORMER:
    TEST:
      PANOPTIC_ON: False
      INSTANCE_ON: False
DATASETS:
  TEST: ("openvocab_ade20k_full_sem_seg_val",)